-- MySQL Script generated by MySQL Workbench
-- Sat Mar 11 18:05:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema EncuestaMacro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EncuestaMacro
-- -----------------------------------------------------
CREATE DATABASE  EncuestaMacro;
USE EncuestaMacro ;

-- -----------------------------------------------------
-- Table EncuestaMacro..provincias
-- -----------------------------------------------------
CREATE TABLE  EncuestaMacro..provincias (
  IdProvincia INT NOT NULL,
  Nombre VARCHAR(45) NULL,
  PRIMARY KEY (IdProvincia))
GO 



-- -----------------------------------------------------
-- Table EncuestaMacro..cantones
-- -----------------------------------------------------
CREATE TABLE  EncuestaMacro..cantones (
  IdCanton INT NOT NULL,
  IdProvinciaFK INT NOT NULL,
  Nombre VARCHAR(45) NULL,
  INDEX fk_Canton_Provincia_idx (IdProvinciaFK ASC),
  PRIMARY KEY (IdCanton),
  CONSTRAINT fk_Canton_Provincia
    FOREIGN KEY (IdProvinciaFK)
    REFERENCES EncuestaMacro..provincias (IdProvincia)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  GO 



-- -----------------------------------------------------
-- Table EncuestaMacro..sucursales
-- -----------------------------------------------------
CREATE TABLE  EncuestaMacro..sucursales (
  IdSucursal INT NOT NULL,
  Sucursal VARCHAR(200) NULL,
  IdCantonFK INT NOT NULL,
  INDEX fk_Sucursal_Canton_idx (IdCantonFK ASC),
  PRIMARY KEY (IdSucursal),
  CONSTRAINT fk_Sucursal_Canton
    FOREIGN KEY (IdCantonFK)
    REFERENCES EncuestaMacro..cantones (IdCanton)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
GO



-- -----------------------------------------------------
-- Table EncuestaMacro..Cliente
-- -----------------------------------------------------
CREATE TABLE  EncuestaMacro..clientes (
  IdPregunta INT NOT NULL AUTO_INCREMT,
  idCliente INT NOT NULL ,
  Cedula VARCHAR(10) NULL,
  Nombre VARCHAR(45) NULL,
  Apellido VARCHAR(45) NULL,
  Sexo VARCHAR(10) NULL,
  Edad VARCHAR(5) NULL,
  PRIMARY KEY (idCliente))
GO


-- -----------------------------------------------------
-- Table EncuestaMacro..Escala
-- -----------------------------------------------------
CREATE TABLE  EncuestaMacro..escalas (
  IdEscala INT NOT NULL,
  ValorInicial VARCHAR(45) NULL,
  ValorFinal VARCHAR(45) NULL,
  ldCategoria INT NULL,  
  PRIMARY KEY (IdEscala))
GO



-- -----------------------------------------------------
-- Table EncuestaMacro..Categoria
-- -----------------------------------------------------
CREATE TABLE  EncuestaMacro..categorias (
  IdCategoria INT NOT NULL,
  Categoria VARCHAR(45) NULL,
  IdEscalaFk INT NOT NULL,
  PRIMARY KEY (IdCategoria),
  INDEX fk_Categoria_Escala_idx (IdEscalaFk ASC) ,
  CONSTRAINT fk_Categoria_Escala
    FOREIGN KEY (IdEscalaFk)
    REFERENCES EncuestaMacro..escalas (IdEscala)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  GO



-- -----------------------------------------------------
-- Table EncuestaMacro..Pregunta
-- -----------------------------------------------------
CREATE TABLE  EncuestaMacro..preguntas (
  IdPregunta INT NOT NULL IDENTITY(1,1),
  Pregunta VARCHAR(500) NULL,
  IdCategoriaFK INT NOT NULL,
  PRIMARY KEY (IdPregunta),
  INDEX fk_Pregunta_Categoria_idx (IdCategoriaFK ASC) ,
  CONSTRAINT fk_Pregunta_Categoria
    FOREIGN KEY (IdCategoriaFK)
    REFERENCES EncuestaMacro..categorias (IdCategoria)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  GO



-- -----------------------------------------------------
-- Table EncuestaMacro..Encuesta
-- -----------------------------------------------------
CREATE TABLE  EncuestaMacro..encuestas (
  IdEncuesta INT NOT NULL IDENTITY(1,1),
  Respuesta VARCHAR(800) NULL,
  FechaRegistro DATETIME NULL,
  IdClienteFK INT NOT NULL,
  IdSucursalFK INT NOT NULL,
  IdPreguntaFK INT NOT NULL,
  PRIMARY KEY (IdEncuesta),
  INDEX fk_Encuesta_Cliente1_idx (IdClienteFK ASC) ,
  INDEX fk_Encuesta_Sucursal1_idx (IdSucursalFK ASC) ,
  INDEX fk_Encuesta_Pregunta1_idx (IdPreguntaFK ASC) ,
  CONSTRAINT fk_Encuesta_Cliente1
    FOREIGN KEY (IdClienteFK)
    REFERENCES EncuestaMacro..clientes (idCliente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Encuesta_Sucursal1
    FOREIGN KEY (IdSucursalFK)
    REFERENCES EncuestaMacro..sucursales (IdSucursal)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Encuesta_Pregunta1
    FOREIGN KEY (IdPreguntaFK)
    REFERENCES EncuestaMacro..preguntas (IdPregunta)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- SCRIP INSERT Escala  1
-- -----------------------------------------------------
INSERT INTO escalas (idEscala,ValorInicial,ValorFinal,Comentario,IdCategoriaFK)VALUES (1,'SI','NO',1)
INSERT INTO escalas (idEscala,ValorInicial,ValorFinal,Comentario,IdCategoriaFK)VALUES (2,'0','10',2)
INSERT INTO escalas (idEscala,ValorInicial,ValorFinal,Comentario,IdCategoriaFK)VALUES (2,'1','400',3)
-- -----------------------------------------------------
-- SCRIP INSERT CATEGORIA 2
-- -----------------------------------------------------

INSERT INTO categorias (idCategoria,Categoria,IdEscalaFK)VALUES ('1','ESTÁNDARES',1)
INSERT INTO categorias (idCategoria,Categoria,IdEscalaFK)VALUES ('2','SATISFACCION',2)
INSERT INTO categorias (idCategoria,Categoria,IdEscalaFK)VALUES ('3','RECOMENDACIÓN',3)

-- -----------------------------------------------------
-- SCRIP INSERT PREGUNTAS 3
-- -----------------------------------------------------


INSERT INTO preguntas (Pregunta,IdCategoriaFK)VALUES ('LE DESPACHARON LOS PRODUCTOS REVISANDO LA FACTURA',1)
INSERT INTO preguntas (Pregunta,IdCategoriaFK)VALUES ('LE ENTREGARON LA FACTURA',1)
INSERT INTO preguntas (Pregunta,IdCategoriaFK)VALUES ('LA AMABILIDAD DEL CAJERO',2)
INSERT INTO preguntas (Pregunta,IdCategoriaFK)VALUES ('LA SATSFACIÓN EN GENERAL',2)
INSERT INTO preguntas (Pregunta,IdCategoriaFK)VALUES ('EN QUE NIVEL RECOMEDARÍA A XYZ A AMIGOS O FAMILIARES SIENDO 0 DEFINITIVAMENTE NO RECOMENDARÍA Y 10 SI RECOMENDARÍA',3)
INSERT INTO preguntas (Pregunta,IdCategoriaFK)VALUES ('SUS OBSERVACIONES FINALES POR FAVOR',3)

-- -----------------------------------------------------
-- ELIMINAR TABLAS
-- -----------------------------------------------------
DROP TABLE escalas, categorias, preguntas


-- -----------------------------------------------------
-- Consulta para reportes 
-- -----------------------------------------------------

SELECT s.Sucursal,
	   c.Nombre as Canton,
	   p.Nombre as Provincia,
	   cl.Cedula as Cedula,
	   cl.Nombre as Nombre,
	   cl.Apellido as Apellido,
	   cat.Categoria as  CategoriaPregunta,
	   pre.Pregunta as Pregunta,
	   e.Respuesta as Respuesta,
	   e.FechaRegistro as Fecha
FROM encuestas e 
	JOIN  sucursales s
	 ON (e.IdSucursalFK=s.IdSucursal)
	 JOIN cantones c
	 ON (s.IdCantonFK=c.IdCanton)
	 JOIN provincias p
	 ON (p.IdProvincia=c.IdProvinciaFK)
	 JOIN clientes cl
	 ON (cl.idCliente=e.IdClienteFK)
	 JOIN preguntas pre
	 ON (pre.IdPregunta=e.IdPreguntaFK)
	 JOIN categorias cat
	 ON (cat.IdCategoria=pre.IdCategoriaFK)


-- -----------------------------------------------------
-- Crear Vista
-- -----------------------------------------------------


   
CREATE VIEW reporte_encuestas
as
SELECT s.Sucursal,
	   c.Nombre as Canton,
	   p.Nombre as Provincia,
	   cl.Cedula as Cedula,
	   cl.Nombre as Nombre,
	   cl.Apellido as Apellido,
	   cat.Categoria as  CategoriaPregunta,
	   pre.Pregunta as Pregunta,
	   e.Respuesta as Respuesta
FROM encuestas e 
	JOIN  sucursales s
	 ON (e.IdSucursalFK=s.IdSucursal)
	 JOIN cantones c
	 ON (s.IdCantonFK=c.IdCanton)
	 JOIN provincias p
	 ON (p.IdProvincia=c.IdProvinciaFK)
	 JOIN clientes cl
	 ON (cl.idCliente=e.IdClienteFK)
	 JOIN preguntas pre
	 ON (pre.IdPregunta=e.IdPreguntaFK)
	 JOIN categorias cat
	 ON (cat.IdCategoria=pre.IdCategoriaFK)